### ISSUE TITLE
Aesthetic issues

### ISSUE THREAD

**Issue by alexgleason** [marykatefain/new_personal_site#8]
These are granular so I'm making one issue just for the things that I see.

![screenshot from 2018-10-15 12 14 57](https://user-images.githubusercontent.com/3639540/46963646-3217bb80-d074-11e8-8948-fe80e63f3dbc.png)

Something is wrong here. The subheadline is too small. The header might also be too small. Why is the title italicized? (not against it, but I question it) The subheadline is too wide. Making it bigger might help, but it probably needs a max-width - there's just too much text for one line.

![screenshot from 2018-10-15 12 19 58](https://user-images.githubusercontent.com/3639540/46963836-a5b9c880-d074-11e8-851f-2e5eba2236b1.png)

The body text within cards is way too light. Impossible to see on your phone in the bright sun, or for visually impaired. I'm actually straining on my laptop in a dimly-lit room. You can maybe get away with light text for the tags, but not the main text. It all still seems a little small. The spacing between the title, subtitle, and main text seems wrong. I'd expect the subtitle to be closer to the title and have more space below it. There's also not enough variation in size between the subtitle and the main text.

![screenshot from 2018-10-15 12 23 09](https://user-images.githubusercontent.com/3639540/46964004-17921200-d075-11e8-9619-6deab20943f9.png)

I remember you improved this area already, but something about it still seems off. The circle is really big and goes above the title to the right of it. It doesn't seem to have enough right padding for how large it is. Think of each element on the page having a gravitational pull. The larger it is, the more space you need to counteract how your eyes perceive it. I think this whole area could more visually distinguished from the stuff above it. Maybe give it a background color? Teal?

![screenshot from 2018-10-15 12 27 51](https://user-images.githubusercontent.com/3639540/46964308-c1719e80-d075-11e8-9687-d96987e70216.png)

These centered links are awkward. I would left-align everything. The inverse-pyramid is usually something you wish to avoid. Make the text at the bottom left aligned, italic, and slightly smaller than the rest. You could do that by increasing the font-size of the other elements instead.

![screenshot from 2018-10-15 12 30 08](https://user-images.githubusercontent.com/3639540/46964440-10b7cf00-d076-11e8-8426-5fd730f09d32.png)

Favicon is redundant. This is barely a real issue - consider it a wishlist item. At least you have one. I'd consider picking an emoji (maybe a plant). At the very least I'd consider making it darker because it really gets lost in the tab.

![screenshot from 2018-10-15 12 32 30](https://user-images.githubusercontent.com/3639540/46964560-67250d80-d076-11e8-8a51-293dd4655834.png)

The banner is a *lot* better now, but I think you're still not 100% there. In the context of these page headers, I'm wondering if the nav should actually go on top and the page title should go inside the banner. You could put a "home" thing in the nav. It also just feels *really* wide. I mean, compare it to any other website's nav. The text is verbose (making it take mental effort to decide what to click) and all those lines between them just adds bulk.

How about a plain black bar? Eg

![screenshot from 2018-10-15 12 38 00](https://user-images.githubusercontent.com/3639540/46964890-48734680-d077-11e8-90fb-692267a06277.png)

(not even tooting my own horn, this site wasn't that good. but you get the point.)

Anyway I just nitpicked your new site a lot, but overall I think it's a great improvement. :grin:

**Comment by marykatefain** [comment]
Thank you!

**Comment by marykatefain** [comment]
>  Why is the title italicized?

It's actually not, that's just the font :joy:  Do you think I should keep experimenting with the header font?

**Comment by alexgleason** [comment]
> It's actually not, that's just the font joy Do you think I should keep experimenting with the header font?

You're only importing the italic version. This is your font: https://fonts.google.com/specimen/Karla

In the network tab I'm seeing this: https://fonts.googleapis.com/css?family=Karla:400i|Scope+One

just find that and change it to ?family=Karla|Scope+One

**Comment by marykatefain** [comment]
Oh damnnnn. Thanks!!
